export const apiUrl: string = "https://dashboard.abazeer.sa/api/site/v1/";
export const baseUrl: string = "https://appadvertisements.almasader.net";
export const apiRoutes = {
  login: "/auth/login",
  register: "auth/register",
  sendOtp: "auth/send_otp",
  forgetPasswordOtp: "forget_password/verfication",
  cart: "cart",
  addresses: "addresses",
  news_letter: "news_letter",
  categories_list: "categories/list",
  checkOTP: "/auth/check_otp",
  resetPassword: "auth/rest_password",
  changePassword: "auth/changePassword",
  about: "about",
  countries: "countries",
  cities: "cities",
  products: "products",
  wishlist: "wishlist/toggle",
  faqs: "faqs",
  simpleCategories: "simpleCategories",
  favorites: "wishlist/list",
  brands: "brands",
  static_pages: "static-pages/list",
  static_page: "static-pages",
  updateProfile: "auth/updateProfile",
  setting: "settings",
  blogs: "blogs",
  blog: "blog",
  flash_sale: "products/flash-sale",
  sliders: "sliders",
  banner: "hero-section",
  search: "products/search",
};
